//------------------------------------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------------------------------------

namespace Batterie.Resources {
	using System;
	
	
	/// <summary>
	///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
	/// </summary>
	// Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
	// à l'aide d'un outil, tel que ResGen ou Visual Studio.
	// Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
	// avec l'option /str ou régénérez votre projet VS.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class AppResources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal AppResources() {
		}
		
		/// <summary>
		///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Batterie.Resources.AppResources", typeof(AppResources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
		///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à pin.
		/// </summary>
		public static string AppBarPinButton {
			get {
				return ResourceManager.GetString("AppBarPinButton", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à rate.
		/// </summary>
		public static string AppBarRateButton {
			get {
				return ResourceManager.GetString("AppBarRateButton", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à BATTERY.
		/// </summary>
		public static string ApplicationTitle {
			get {
				return ResourceManager.GetString("ApplicationTitle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à This application is designed to be as simple as possible: no parameter, just the bare necessities..
		/// </summary>
		public static string DetailsFirstLine {
			get {
				return ResourceManager.GetString("DetailsFirstLine", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à PS: The system does not allow to do otherwise, the tile being updated every 30 minutes..
		/// </summary>
		public static string DetailsSecondLine {
			get {
				return ResourceManager.GetString("DetailsSecondLine", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à current state.
		/// </summary>
		public static string FirstPivotItemTitle {
			get {
				return ResourceManager.GetString("FirstPivotItemTitle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Supply source:.
		/// </summary>
		public static string LabelAlimentationSource {
			get {
				return ResourceManager.GetString("LabelAlimentationSource", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Current battery level:.
		/// </summary>
		public static string LabelBattLevel {
			get {
				return ResourceManager.GetString("LabelBattLevel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Time remaining:.
		/// </summary>
		public static string LabelBattRemaining {
			get {
				return ResourceManager.GetString("LabelBattRemaining", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à day.
		/// </summary>
		public static string LabelDay {
			get {
				return ResourceManager.GetString("LabelDay", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à days.
		/// </summary>
		public static string LabelDays {
			get {
				return ResourceManager.GetString("LabelDays", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Details.
		/// </summary>
		public static string LabelDetails {
			get {
				return ResourceManager.GetString("LabelDetails", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à hour.
		/// </summary>
		public static string LabelHour {
			get {
				return ResourceManager.GetString("LabelHour", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à hours.
		/// </summary>
		public static string LabelHours {
			get {
				return ResourceManager.GetString("LabelHours", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à minute.
		/// </summary>
		public static string LabelMinute {
			get {
				return ResourceManager.GetString("LabelMinute", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à minutes.
		/// </summary>
		public static string LabelMinutes {
			get {
				return ResourceManager.GetString("LabelMinutes", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Battery.
		/// </summary>
		public static string LabelPowerSourceBattery {
			get {
				return ResourceManager.GetString("LabelPowerSourceBattery", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à External.
		/// </summary>
		public static string LabelPowerSourceExternal {
			get {
				return ResourceManager.GetString("LabelPowerSourceExternal", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Version.
		/// </summary>
		public static string LabelVersion {
			get {
				return ResourceManager.GetString("LabelVersion", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à d.
		/// </summary>
		public static string LetterDay {
			get {
				return ResourceManager.GetString("LetterDay", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à h.
		/// </summary>
		public static string LetterHour {
			get {
				return ResourceManager.GetString("LetterHour", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à m.
		/// </summary>
		public static string LetterMinute {
			get {
				return ResourceManager.GetString("LetterMinute", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à en.
		/// </summary>
		public static string ResourceLanguage {
			get {
				return ResourceManager.GetString("ResourceLanguage", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Your opinion about battery.
		/// </summary>
		public static string ReviewCaption {
			get {
				return ResourceManager.GetString("ReviewCaption", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à You enjoy use battery?.
		/// </summary>
		public static string ReviewMessageFirstLine {
			get {
				return ResourceManager.GetString("ReviewMessageFirstLine", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à Take a second to rate it. Thanks :).
		/// </summary>
		public static string ReviewMessageSecondLine {
			get {
				return ResourceManager.GetString("ReviewMessageSecondLine", resourceCulture);
			}
		}
		
		/// <summary>
		///   Recherche une chaîne localisée semblable à about....
		/// </summary>
		public static string SecondPivotItemTitle {
			get {
				return ResourceManager.GetString("SecondPivotItemTitle", resourceCulture);
			}
		}
	}
}
